In [1]:
import copy
import numpy as np
import open3d as o3d

In [2]:
x = np.linspace(-3, 3, 401)
mesh_x, mesh_y = np.meshgrid(x, x)
z = np.sinc((np.power(mesh_x, 2) + np.power(mesh_y, 2)))
z_norm = (z - z.min()) / (z.max() - z.min())
xyz = np.zeros((np.size(mesh_x), 3))
xyz[:, 0] = np.reshape(mesh_x, -1)
xyz[:, 1] = np.reshape(mesh_y, -1)
xyz[:, 2] = np.reshape(z_norm, -1)
print('xyz')
print(xyz)

xyz
[[-3.         -3.          0.17846472]
 [-2.985      -3.          0.17440115]
 [-2.97       -3.          0.17063709]
 ...
 [ 2.97        3.          0.17063709]
 [ 2.985       3.          0.17440115]
 [ 3.          3.          0.17846472]]


In [3]:
xyz.shape

(160801, 3)

In [4]:
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(xyz)

In [9]:
T = np.array([[0.999968402, -0.006753626, -0.004188075, -0.015890727],
              [-0.006685408, -0.999848172, 0.016093893, 0.028273059],
              [-0.004296131, -0.016065384, -0.999861654, -0.009375589],
              [0, 0, 0, 1]])

In [10]:
T

array([[ 0.9999684 , -0.00675363, -0.00418808, -0.01589073],
       [-0.00668541, -0.99984817,  0.01609389,  0.02827306],
       [-0.00429613, -0.01606538, -0.99986165, -0.00937559],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [11]:
np.save('T265toD435.npy', T)

In [12]:
# tm_T265toD435 = np.load('confings/T265toD435.npy')
tm_T265toD435 = np.load('T265toD435.npy')

In [13]:
tm_T265toD435

array([[ 0.9999684 , -0.00675363, -0.00418808, -0.01589073],
       [-0.00668541, -0.99984817,  0.01609389,  0.02827306],
       [-0.00429613, -0.01606538, -0.99986165, -0.00937559],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])